spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_DATABASE_URL}
    username: ${MYSQL_DATABASE_USERNAME}
    password: ${MYSQL_DATABASE_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true
    database: mysql

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

logging:
  level:
    root: info
    com.record.the_record: info

openvidu:
  url: ${OPENVIDU_URL}
  secret: ${OPENVIDU_SECRET}

server:
  ssl:
    key-store: classpath:openvidu-selfsigned.jks
    key-store-password: openvidu
    key-store-type: JKS
    key-alias: openvidu-selfsigned